import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import React, { useState } from 'react'
import { Test } from '../components/showtext'
import { Result, Selected } from '../components/types'
import { ModalInitTest } from '../components/modalinit'

const Home: NextPage = () => {
  const [selectedOptions, setSelectedOptions] = useState<Selected>({
    mode: "easyMode.txt",
    time: "1"
  });
  const [dataText, setDataText] = useState<string[]>([]);
  const [result, setResult] = useState<Result>({
    errs: -1,
    success: -1
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Typing speed test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossOrigin="anonymous"></link>
      </Head>

      <main className={styles.main}>
        {dataText.length === 0 &&
          <ModalInitTest selectedOptions={selectedOptions} setSelectedOptions={setSelectedOptions} setDataText={setDataText} result={result} />
        }
        {dataText.length !== 0 &&
          <Test dataText={dataText} selectedOptions={selectedOptions} setResult={setResult} setDataText={setDataText} />
        }
      </main>

      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossOrigin="anonymous" />
    </div>
  )
}

export default Home
